version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    build:
      context: .
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      TYPE: SPIGOT
      VERSION: LATEST    
      CONSOLE: "false"
      ENABLE_RCON: "false"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
    restart: always



